version: 0.2

env:
  shell: bash

phases:
  build:
    commands:
      - set -e
      - cat > deploy_key <<'EOF'
        ${DEPLOY_KEY}
        EOF
      - echo "Host github.com" > config
      - echo "  IdentityFile {workdir}/deploy_key" >> config
      - echo "  StrictHostKeyChecking no" >> config
      - chmod 400 deploy_key

artifacts:
  files:
    - "**/*"
  secondary-artifacts:
    ssh_config:
      base-directory: $CODEBUILD_SRC_DIR

