version: 0.2

env:
  shell: bash

phases:
  build:
    commands:
      - set -e
      - cat > deploy_key <<'EOF'
        ${DEPLOY_KEY}
        EOF
      - echo "Host github.com" > config
      - echo "  IdentityFile {workdir}/deploy_key" >> config
      - echo "  StrictHostKeyChecking no" >> config
      - chmod 400 deploy_key

artifacts:
  name: ssh_config
  files:
    - deploy_key
    - config
  discard-paths: no
  base-directory: CODEBUILD_SRC_DIR

